/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.18.0_1/nim/lib -o /Users/mlauwers/Downloads/nim/src/nimcache/nim_nim.o /Users/mlauwers/Downloads/nim/src/nimcache/nim_nim.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w;
typedef struct tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg;
typedef struct tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug;
typedef struct tyObject_FpsManager_K9c6YTNaeSVqIm8VozHdXPQ tyObject_FpsManager_K9c6YTNaeSVqIm8VozHdXPQ;
typedef NI32 tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw;
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_fvOXafK39cW5YZA9b9bzinu9cw) (int flags);
typedef N_CDECL_PTR(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w*, tyProc_1K9aSViCbSUpZMtRI9aw9a2Rg) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg*, tyProc_eGPD9aEHv9b8sVQMCQaPsYkg) (tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window, int index, int flags);
typedef NI32 tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w;
typedef NU8 tyArray_Y1pDC6KIrpu9aJMBN9aOQMhw[52];
struct tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug {
tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
tyArray_Y1pDC6KIrpu9aJMBN9aOQMhw padding;
};
struct tyObject_FpsManager_K9c6YTNaeSVqIm8VozHdXPQ {
int framecount;
float rateticks;
int baseticks;
int lastticks;
int rate;
};
typedef N_CDECL_PTR(void, tyProc_cfgfzj4BFRc9cgaCE88zYLQ) (tyObject_FpsManager_K9c6YTNaeSVqIm8VozHdXPQ* manager);
typedef NI32 tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg;
typedef N_CDECL_PTR(tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg, tyProc_b9aXpKFbsyZ0PIk3aYRVCAA) (tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug* event);
typedef N_CDECL_PTR(int, tyProc_2nApE2oRVV9bdZ01fOBEbDg) (tyObject_FpsManager_K9c6YTNaeSVqIm8VozHdXPQ* manager);
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_BzAZji9bzvN1k9ae25rIlb8A) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, tyProc_zHpDbFN4o9bvP9cAphXAUHXg) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer);
typedef N_CDECL_PTR(void, tyProc_9a8AalbnAaIxTUMpzQQqpjw) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer);
typedef N_CDECL_PTR(void, tyProc_T629bWTbvDFNyKAaO0BGGIQ) (tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
struct tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w {
char dummy;
};
struct tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg {
char dummy;
};
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, toBool_3fq5Y9cfgYx8q7J9ba6TTYbQ)(tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg some);
static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, destroy_sFvfWODyHxg46OuBtGyU8Qnim)(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_gfxInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_gfxDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, nimDatInit000)(void);
extern tyProc_fvOXafK39cW5YZA9b9bzinu9cw Dl_146765_;
tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window_wBq5aDTF8DhtU9aLu9boxSKg;
tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* render_pr3vi7Yjghf9b9aEJilJ7cOQ;
extern tyProc_1K9aSViCbSUpZMtRI9aw9a2Rg Dl_147356_;
extern tyProc_eGPD9aEHv9b8sVQMCQaPsYkg Dl_146811_;
tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug evt_aaAz4Dv1HcmcHYLKdUgDDQ;
extern tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ;
NIM_BOOL runGame_cYKTVzG9cz6Uqja3VU33Orw;
tyObject_FpsManager_K9c6YTNaeSVqIm8VozHdXPQ fpsman_9aVcaOzPnl79b10IuIkny5Ow;
extern tyProc_cfgfzj4BFRc9cgaCE88zYLQ Dl_150222_;
extern tyProc_b9aXpKFbsyZ0PIk3aYRVCAA Dl_147605_;
NF dt_wheMoUEDvgeffRCDyiZjzQ;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyProc_2nApE2oRVV9bdZ01fOBEbDg Dl_150231_;
extern tyProc_BzAZji9bzvN1k9ae25rIlb8A Dl_146617_;
extern tyProc_zHpDbFN4o9bvP9cAphXAUHXg Dl_147017_;
extern tyProc_9a8AalbnAaIxTUMpzQQqpjw Dl_147036_;
extern tyProc_2nApE2oRVV9bdZ01fOBEbDg Dl_150239_;
extern tyProc_9a8AalbnAaIxTUMpzQQqpjw Dl_146648_;
extern tyProc_T629bWTbvDFNyKAaO0BGGIQ Dl_147388_;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y) {
	NF result;
	nimfr_("/", "system.nim");
	result = (NF)0;
	nimln_(3498, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

static N_INLINE(void, destroy_sFvfWODyHxg46OuBtGyU8Qnim)(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window) {
	nimfr_("destroy", "sdl2.nim");
	nimln_(1742, "sdl2.nim");
	Dl_147388_(window);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_unsignedDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	sdl2_sdl2DatInit000();
	sdl2_gfxDatInit000();
	nimDatInit000();
	stdlib_macrosInit000();
	stdlib_unsignedInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	sdl2_sdl2Init000();
	sdl2_gfxInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw T1_;
	nimfr_("nim", "nim.nim");
	nimln_(4, "nim.nim");
	T1_ = (tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
	T1_ = Dl_146765_(((int) 65535));
	T1_;
	nimln_(10, "nim.nim");
	window_wBq5aDTF8DhtU9aLu9boxSKg = Dl_147356_("SDL Skeleton", ((int) 100), ((int) 100), ((int) 640), ((int) 480), ((unsigned int) 4));
	nimln_(11, "nim.nim");
	render_pr3vi7Yjghf9b9aEJilJ7cOQ = Dl_146811_(window_wBq5aDTF8DhtU9aLu9boxSKg, ((int) -1), ((NI32) 14));
	nimln_(14, "nim.nim");
	evt_aaAz4Dv1HcmcHYLKdUgDDQ = defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ;
	nimln_(15, "nim.nim");
	runGame_cYKTVzG9cz6Uqja3VU33Orw = NIM_TRUE;
	nimln_(17, "nim.nim");
	Dl_150222_((&fpsman_9aVcaOzPnl79b10IuIkny5Ow));
	{
		nimln_(19, "nim.nim");
		while (1) {
			int T12_;
			tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw T13_;
			int T14_;
			int T15_;
			if (!runGame_cYKTVzG9cz6Uqja3VU33Orw) goto LA3;
			{
				nimln_(20, "nim.nim");
				while (1) {
					tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg T6_;
					NIM_BOOL T7_;
					T6_ = (tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg)0;
					T6_ = Dl_147605_((&evt_aaAz4Dv1HcmcHYLKdUgDDQ));
					T7_ = (NIM_BOOL)0;
					T7_ = toBool_3fq5Y9cfgYx8q7J9ba6TTYbQ(T6_);
					if (!T7_) goto LA5;
					nimln_(21, "nim.nim");
					{
						if (!(evt_aaAz4Dv1HcmcHYLKdUgDDQ.kind == ((tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 256))) goto LA10_;
						nimln_(22, "nim.nim");
						runGame_cYKTVzG9cz6Uqja3VU33Orw = NIM_FALSE;
						nimln_(23, "nim.nim");
						goto LA4;
					}
					LA10_: ;
				} LA5: ;
			} LA4: ;
			dt_wheMoUEDvgeffRCDyiZjzQ = 0;
			nimln_(25, "nim.nim");
			T12_ = (int)0;
			T12_ = Dl_150231_((&fpsman_9aVcaOzPnl79b10IuIkny5Ow));
			dt_wheMoUEDvgeffRCDyiZjzQ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(((NI) (T12_)), ((NI) 1000));
			nimln_(27, "nim.nim");
			T13_ = (tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
			T13_ = Dl_146617_(render_pr3vi7Yjghf9b9aEJilJ7cOQ, ((NU8) 0), ((NU8) 0), ((NU8) 0), ((NU8) 255));
			nimln_(28, "nim.nim");
			T14_ = (int)0;
			T14_ = Dl_147017_(render_pr3vi7Yjghf9b9aEJilJ7cOQ);
			nimln_(30, "nim.nim");
			Dl_147036_(render_pr3vi7Yjghf9b9aEJilJ7cOQ);
			nimln_(31, "nim.nim");
			T15_ = (int)0;
			T15_ = Dl_150239_((&fpsman_9aVcaOzPnl79b10IuIkny5Ow));
		} LA3: ;
	}
	nimln_(33, "nim.nim");
	Dl_146648_(render_pr3vi7Yjghf9b9aEJilJ7cOQ);
	nimln_(34, "nim.nim");
	destroy_sFvfWODyHxg46OuBtGyU8Qnim(window_wBq5aDTF8DhtU9aLu9boxSKg);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimDatInit000)(void) {
}

