/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.18.0_1/nim/lib -o /Users/mlauwers/Development/nim/nim_tetris/src/nimcache/sdl2_sdl2.o /Users/mlauwers/Development/nim/nim_tetris/src/nimcache/sdl2_sdl2.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w;
typedef struct tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg;
typedef struct tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ;
typedef struct tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw;
typedef struct tyTuple_rTI1z5tLuTbP9b133u2ve6A tyTuple_rTI1z5tLuTbP9b133u2ve6A;
typedef struct tyObject_KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ tyObject_KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ;
typedef struct tyObject_KeySym_y3t7PyKCT9aYLDh9bLHT3UPw tyObject_KeySym_y3t7PyKCT9aYLDh9bLHT3UPw;
typedef NI32 tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w;
typedef NU8 tyArray_Y1pDC6KIrpu9aJMBN9aOQMhw[52];
struct tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug {
tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
tyArray_Y1pDC6KIrpu9aJMBN9aOQMhw padding;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NI32 tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw;
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_fvOXafK39cW5YZA9b9bzinu9cw) (int flags);
typedef N_CDECL_PTR(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w*, tyProc_1K9aSViCbSUpZMtRI9aw9a2Rg) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg*, tyProc_eGPD9aEHv9b8sVQMCQaPsYkg) (tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window, int index, int flags);
struct tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ {
int Field0;
int Field1;
int Field2;
int Field3;
};
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_uEPg0xGcL9ao0XgF3q7VnpA) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ* srcrect, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ* dstrect, double angle, tyTuple_rTI1z5tLuTbP9b133u2ve6A* center, int flip);
typedef NI32 tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg;
typedef N_CDECL_PTR(tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg, tyProc_b9aXpKFbsyZ0PIk3aYRVCAA) (tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug* event);
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_BzAZji9bzvN1k9ae25rIlb8A) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, tyProc_zHpDbFN4o9bvP9cAphXAUHXg) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer);
typedef N_CDECL_PTR(void, tyProc_9a8AalbnAaIxTUMpzQQqpjw) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer);
typedef N_CDECL_PTR(void, tyProc_T629bWTbvDFNyKAaO0BGGIQ) (tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
struct tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w {
char dummy;
};
struct tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg {
char dummy;
};
struct tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw {
char dummy;
};
struct tyTuple_rTI1z5tLuTbP9b133u2ve6A {
int Field0;
int Field1;
};
typedef NI32 tyEnum_Scancode_ZC4j1APU9aAJPXuZfLFUG0w;
struct tyObject_KeySym_y3t7PyKCT9aYLDh9bLHT3UPw {
tyEnum_Scancode_ZC4j1APU9aAJPXuZfLFUG0w scancode;
int sym;
NI16 modstate;
int unicode;
};
struct tyObject_KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ {
tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
NU32 timestamp;
NU32 windowID;
NU8 state;
NIM_BOOL repeat;
NU8 pad1;
NU8 pad2;
tyObject_KeySym_y3t7PyKCT9aYLDh9bLHT3UPw keysym;
};
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ;
TNimType NTI_Uzh9aP43ffUpM9aa6vZvNEug_;
TNimType NTI_9ayvRjKFMoE6pV9bOp5OUI5w_;
extern TNimType NTI_k3HXouOuhqAKq0dx450lXQ_;
TNimType NTI_Y1pDC6KIrpu9aJMBN9aOQMhw_;
static void* TM_ZcjcXgoBjElsmUGY1Ljosg_6;
tyProc_fvOXafK39cW5YZA9b9bzinu9cw Dl_168765_;
tyProc_1K9aSViCbSUpZMtRI9aw9a2Rg Dl_169356_;
tyProc_eGPD9aEHv9b8sVQMCQaPsYkg Dl_168811_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
tyProc_uEPg0xGcL9ao0XgF3q7VnpA Dl_168995_;
tyProc_b9aXpKFbsyZ0PIk3aYRVCAA Dl_169605_;
tyProc_BzAZji9bzvN1k9ae25rIlb8A Dl_168617_;
tyProc_zHpDbFN4o9bvP9cAphXAUHXg Dl_169017_;
tyProc_9a8AalbnAaIxTUMpzQQqpjw Dl_169036_;
tyProc_9a8AalbnAaIxTUMpzQQqpjw Dl_168648_;
tyProc_T629bWTbvDFNyKAaO0BGGIQ Dl_169388_;
STRING_LITERAL(TM_ZcjcXgoBjElsmUGY1Ljosg_8, "libSDL2.dylib", 13);
STRING_LITERAL(TM_ZcjcXgoBjElsmUGY1Ljosg_9, "libSDL2.dylib", 13);
STRING_LITERAL(TM_ZcjcXgoBjElsmUGY1Ljosg_20, "contains({KeyDown, KeyUp}, event160407.kind) ", 45);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_CDECL(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, rect_GH33Rh9bTnVBRLuu9bU7xoyA)(int x, int y, int w, int h) {
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ result;
	nimfr_("rect", "sdl2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(1766, "sdl2.nim");
	result.Field0 = x;
	nimln_(1767, "sdl2.nim");
	result.Field1 = y;
	nimln_(1768, "sdl2.nim");
	result.Field2 = w;
	nimln_(1769, "sdl2.nim");
	result.Field3 = h;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, toBool_3fq5Y9cfgYx8q7J9ba6TTYbQ)(tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg some) {
	NIM_BOOL result;
	nimfr_("toBool", "sdl2.nim");
	result = (NIM_BOOL)0;
	nimln_(330, "sdl2.nim");
	result = ((NIM_BOOL) (some));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ*, key_Sy9cYLza36NW1QN9asfW9a0LA)(tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug* event) {
	tyObject_KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ* result;
	nimfr_("key", "sdl2.nim");
{	result = (tyObject_KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ*)0;
	nimln_(616, "sdl2.nim");
	{
		if (!!(((*event).kind == ((tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 768) || (*event).kind == ((tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 769)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_ZcjcXgoBjElsmUGY1Ljosg_20));
	}
	LA3_: ;
	nimln_(617, "sdl2.nim");
	result = ((tyObject_KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ*) (event));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init000)(void) {
	nimfr_("sdl2", "sdl2.nim");
	nimln_(1800, "sdl2.nim");
	chckNil((void*)(&defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ));
	genericReset((void*)(&defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ), (&NTI_Uzh9aP43ffUpM9aa6vZvNEug_));
	defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ.kind = ((tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 256);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit000)(void) {
static TNimNode* TM_ZcjcXgoBjElsmUGY1Ljosg_2[2];
static TNimNode* TM_ZcjcXgoBjElsmUGY1Ljosg_3[44];
NI TM_ZcjcXgoBjElsmUGY1Ljosg_5;
static char* NIM_CONST TM_ZcjcXgoBjElsmUGY1Ljosg_4[44] = {
"QuitEvent", 
"AppTerminating", 
"AppLowMemory", 
"AppWillEnterBackground", 
"AppDidEnterBackground", 
"AppWillEnterForeground", 
"AppDidEnterForeground", 
"WindowEvent", 
"SysWMEvent", 
"KeyDown", 
"KeyUp", 
"TextEditing", 
"TextInput", 
"MouseMotion", 
"MouseButtonDown", 
"MouseButtonUp", 
"MouseWheel", 
"JoyAxisMotion", 
"JoyBallMotion", 
"JoyHatMotion", 
"JoyButtonDown", 
"JoyButtonUp", 
"JoyDeviceAdded", 
"JoyDeviceRemoved", 
"ControllerAxisMotion", 
"ControllerButtonDown", 
"ControllerButtonUp", 
"ControllerDeviceAdded", 
"ControllerDeviceRemoved", 
"ControllerDeviceRemapped", 
"FingerDown", 
"FingerUp", 
"FingerMotion", 
"DollarGesture", 
"DollarRecord", 
"MultiGesture", 
"ClipboardUpdate", 
"DropFile", 
"UserEvent", 
"UserEvent1", 
"UserEvent2", 
"UserEvent3", 
"UserEvent4", 
"UserEvent5"};
static TNimNode TM_ZcjcXgoBjElsmUGY1Ljosg_0[48];
NTI_Uzh9aP43ffUpM9aa6vZvNEug_.size = sizeof(tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug);
NTI_Uzh9aP43ffUpM9aa6vZvNEug_.kind = 18;
NTI_Uzh9aP43ffUpM9aa6vZvNEug_.base = 0;
NTI_Uzh9aP43ffUpM9aa6vZvNEug_.flags = 3;
TM_ZcjcXgoBjElsmUGY1Ljosg_2[0] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[1];
NTI_9ayvRjKFMoE6pV9bOp5OUI5w_.size = sizeof(tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w);
NTI_9ayvRjKFMoE6pV9bOp5OUI5w_.kind = 14;
NTI_9ayvRjKFMoE6pV9bOp5OUI5w_.base = 0;
NTI_9ayvRjKFMoE6pV9bOp5OUI5w_.flags = 3;
for (TM_ZcjcXgoBjElsmUGY1Ljosg_5 = 0; TM_ZcjcXgoBjElsmUGY1Ljosg_5 < 44; TM_ZcjcXgoBjElsmUGY1Ljosg_5++) {
TM_ZcjcXgoBjElsmUGY1Ljosg_0[TM_ZcjcXgoBjElsmUGY1Ljosg_5+2].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[TM_ZcjcXgoBjElsmUGY1Ljosg_5+2].offset = TM_ZcjcXgoBjElsmUGY1Ljosg_5;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[TM_ZcjcXgoBjElsmUGY1Ljosg_5+2].name = TM_ZcjcXgoBjElsmUGY1Ljosg_4[TM_ZcjcXgoBjElsmUGY1Ljosg_5];
TM_ZcjcXgoBjElsmUGY1Ljosg_3[TM_ZcjcXgoBjElsmUGY1Ljosg_5] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[TM_ZcjcXgoBjElsmUGY1Ljosg_5+2];
}
TM_ZcjcXgoBjElsmUGY1Ljosg_0[2].offset = 256;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[3].offset = 257;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[4].offset = 258;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[5].offset = 259;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[6].offset = 260;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[7].offset = 261;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[8].offset = 262;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[9].offset = 512;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[10].offset = 513;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[11].offset = 768;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[12].offset = 769;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[13].offset = 770;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[14].offset = 771;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[15].offset = 1024;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[16].offset = 1025;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[17].offset = 1026;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[18].offset = 1027;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[19].offset = 1536;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[20].offset = 1537;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[21].offset = 1538;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[22].offset = 1539;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[23].offset = 1540;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[24].offset = 1541;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[25].offset = 1542;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[26].offset = 1616;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[27].offset = 1617;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[28].offset = 1618;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[29].offset = 1619;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[30].offset = 1620;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[31].offset = 1621;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[32].offset = 1792;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[33].offset = 1793;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[34].offset = 1794;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[35].offset = 2048;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[36].offset = 2049;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[37].offset = 2050;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[38].offset = 2304;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[39].offset = 4096;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[40].offset = 32768;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[41].offset = 32769;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[42].offset = 32770;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[43].offset = 32771;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[44].offset = 32772;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[45].offset = 32773;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[46].len = 44; TM_ZcjcXgoBjElsmUGY1Ljosg_0[46].kind = 2; TM_ZcjcXgoBjElsmUGY1Ljosg_0[46].sons = &TM_ZcjcXgoBjElsmUGY1Ljosg_3[0];
NTI_9ayvRjKFMoE6pV9bOp5OUI5w_.node = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[46];
NTI_9ayvRjKFMoE6pV9bOp5OUI5w_.flags = 1<<2;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[1].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[1].offset = offsetof(tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug, kind);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[1].typ = (&NTI_9ayvRjKFMoE6pV9bOp5OUI5w_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[1].name = "kind";
TM_ZcjcXgoBjElsmUGY1Ljosg_2[1] = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[47];
NTI_Y1pDC6KIrpu9aJMBN9aOQMhw_.size = sizeof(tyArray_Y1pDC6KIrpu9aJMBN9aOQMhw);
NTI_Y1pDC6KIrpu9aJMBN9aOQMhw_.kind = 16;
NTI_Y1pDC6KIrpu9aJMBN9aOQMhw_.base = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
NTI_Y1pDC6KIrpu9aJMBN9aOQMhw_.flags = 3;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[47].kind = 1;
TM_ZcjcXgoBjElsmUGY1Ljosg_0[47].offset = offsetof(tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug, padding);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[47].typ = (&NTI_Y1pDC6KIrpu9aJMBN9aOQMhw_);
TM_ZcjcXgoBjElsmUGY1Ljosg_0[47].name = "padding";
TM_ZcjcXgoBjElsmUGY1Ljosg_0[0].len = 2; TM_ZcjcXgoBjElsmUGY1Ljosg_0[0].kind = 2; TM_ZcjcXgoBjElsmUGY1Ljosg_0[0].sons = &TM_ZcjcXgoBjElsmUGY1Ljosg_2[0];
NTI_Uzh9aP43ffUpM9aa6vZvNEug_.node = &TM_ZcjcXgoBjElsmUGY1Ljosg_0[0];
if (!((TM_ZcjcXgoBjElsmUGY1Ljosg_6 = nimLoadLibrary((NimStringDesc*) &TM_ZcjcXgoBjElsmUGY1Ljosg_8))
)) nimLoadLibraryError((NimStringDesc*) &TM_ZcjcXgoBjElsmUGY1Ljosg_9);
	Dl_168765_ = (tyProc_fvOXafK39cW5YZA9b9bzinu9cw) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_6, "SDL_Init");
	Dl_169356_ = (tyProc_1K9aSViCbSUpZMtRI9aw9a2Rg) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_6, "SDL_CreateWindow");
	Dl_168811_ = (tyProc_eGPD9aEHv9b8sVQMCQaPsYkg) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_6, "SDL_CreateRenderer");
	Dl_168995_ = (tyProc_uEPg0xGcL9ao0XgF3q7VnpA) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_6, "SDL_RenderCopyEx");
	Dl_169605_ = (tyProc_b9aXpKFbsyZ0PIk3aYRVCAA) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_6, "SDL_PollEvent");
	Dl_168617_ = (tyProc_BzAZji9bzvN1k9ae25rIlb8A) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_6, "SDL_SetRenderDrawColor");
	Dl_169017_ = (tyProc_zHpDbFN4o9bvP9cAphXAUHXg) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_6, "SDL_RenderClear");
	Dl_169036_ = (tyProc_9a8AalbnAaIxTUMpzQQqpjw) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_6, "SDL_RenderPresent");
	Dl_168648_ = (tyProc_9a8AalbnAaIxTUMpzQQqpjw) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_6, "SDL_DestroyRenderer");
	Dl_169388_ = (tyProc_T629bWTbvDFNyKAaO0BGGIQ) nimGetProcAddr(TM_ZcjcXgoBjElsmUGY1Ljosg_6, "SDL_DestroyWindow");
}

