/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.18.0_1/nim/lib -o /Users/mlauwers/Downloads/nim/src/nimcache/tetris_tetris.o /Users/mlauwers/Downloads/nim/src/nimcache/tetris_tetris.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w;
typedef struct tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg;
typedef struct tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw;
typedef struct tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ;
typedef struct tyTuple_rTI1z5tLuTbP9b133u2ve6A tyTuple_rTI1z5tLuTbP9b133u2ve6A;
typedef struct tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug;
typedef struct tyObject_FpsManager_K9c6YTNaeSVqIm8VozHdXPQ tyObject_FpsManager_K9c6YTNaeSVqIm8VozHdXPQ;
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
typedef tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyArray_oxvy57QiwK9c9a12Qd7kQzlQ[4];
typedef tyArray_oxvy57QiwK9c9a12Qd7kQzlQ tyArray_tBzCxVJJXe7fyzaDdi730A[4];
typedef NU8 tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg;
typedef tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg tyArray_dGkDOlaIzDUcymySNQBeNg[10];
typedef tyArray_dGkDOlaIzDUcymySNQBeNg tyArray_A4GTsBKrn1StyjIPYWAj9bw[20];
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA;
typedef NU8 tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ;
typedef NI32 tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw;
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_fvOXafK39cW5YZA9b9bzinu9cw) (int flags);
typedef N_CDECL_PTR(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w*, tyProc_1K9aSViCbSUpZMtRI9aw9a2Rg) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg*, tyProc_eGPD9aEHv9b8sVQMCQaPsYkg) (tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window, int index, int flags);
typedef N_CDECL_PTR(tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw*, tyProc_0icUM9coigCdz0HL3vd9bFCw) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, NCSTRING file);
struct tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ {
int Field0;
int Field1;
int Field2;
int Field3;
};
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_uEPg0xGcL9ao0XgF3q7VnpA) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ* srcrect, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ* dstrect, double angle, tyTuple_rTI1z5tLuTbP9b133u2ve6A* center, int flip);
typedef NI32 tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w;
typedef NU8 tyArray_Y1pDC6KIrpu9aJMBN9aOQMhw[52];
struct tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug {
tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
tyArray_Y1pDC6KIrpu9aJMBN9aOQMhw padding;
};
struct tyObject_FpsManager_K9c6YTNaeSVqIm8VozHdXPQ {
int framecount;
float rateticks;
int baseticks;
int lastticks;
int rate;
};
typedef N_CDECL_PTR(void, tyProc_cfgfzj4BFRc9cgaCE88zYLQ) (tyObject_FpsManager_K9c6YTNaeSVqIm8VozHdXPQ* manager);
typedef NI32 tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg;
typedef N_CDECL_PTR(tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg, tyProc_b9aXpKFbsyZ0PIk3aYRVCAA) (tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug* event);
typedef N_CDECL_PTR(int, tyProc_2nApE2oRVV9bdZ01fOBEbDg) (tyObject_FpsManager_K9c6YTNaeSVqIm8VozHdXPQ* manager);
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_BzAZji9bzvN1k9ae25rIlb8A) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, tyProc_zHpDbFN4o9bvP9cAphXAUHXg) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer);
typedef N_CDECL_PTR(void, tyProc_9a8AalbnAaIxTUMpzQQqpjw) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer);
typedef N_CDECL_PTR(void, tyProc_T629bWTbvDFNyKAaO0BGGIQ) (tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
struct tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w {
char dummy;
};
struct tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg {
char dummy;
};
struct tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw {
char dummy;
};
struct tyTuple_rTI1z5tLuTbP9b133u2ve6A {
int Field0;
int Field1;
};
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isBlockAt_4b9clJUjy444rNQS4Pl9ccHw)(tyArray_A4GTsBKrn1StyjIPYWAj9bw board, NU x, NU y);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, dropBlockAt_KP9aYeB9cuk5QYM2zV2M2E9cA)(tyArray_dGkDOlaIzDUcymySNQBeNg* board, NU x, NU y);
N_LIB_PRIVATE N_NIMCALL(tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA, rotateLeft_WhYUm29bN1IvB6kJwPoZzIg)(tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA currentRotation);
N_LIB_PRIVATE N_NIMCALL(tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA, rotateRight_WhYUm29bN1IvB6kJwPoZzIg_2)(tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA currentRotation);
N_LIB_PRIVATE N_NIMCALL(tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ, generateTetronimoType_O9atHRoChfVK9bcx9cFIsM4nA)(void);
N_LIB_PRIVATE N_NIMCALL(void, randomize_RtUZt2O8eA6Y5pFWOsdgjg)(void);
N_LIB_PRIVATE N_NIMCALL(NI, rand_F1qFFP53BvbP4L65Kn9bG1w_2)(NI max);
N_LIB_PRIVATE N_NIMCALL(void, newTetronimo_rx8mlrdpgisQw9aihwsqf6A)(tyArray_tBzCxVJJXe7fyzaDdi730A Result);
N_NOINLINE(void, chckNil)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, insertShape_9ce7hHobx9a9cOfNVjg17o7zQ)(tyArray_dGkDOlaIzDUcymySNQBeNg* board, tyArray_tBzCxVJJXe7fyzaDdi730A Result);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, getBlockTexture_zOaZQisd5oWhqujp21WGMQ)(tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg color);
N_LIB_PRIVATE N_CDECL(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, rect_GH33Rh9bTnVBRLuu9bU7xoyA)(int x, int y, int w, int h);
N_LIB_PRIVATE N_NIMCALL(void, drawBlock_lNcFlsekAhGuxAXvCEQ87A)(tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg color, NU x, NU y);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, drawBoard_plavXhyyiBCgWhKKV5uZbA)(tyArray_A4GTsBKrn1StyjIPYWAj9bw board);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, toBool_3fq5Y9cfgYx8q7J9ba6TTYbQ)(tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg some);
static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y);
static N_INLINE(void, destroy_sFvfWODyHxg46OuBtGyU8Qtetris)(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_randomInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_randomDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_gfxInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_gfxDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, tetrisDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyProc_fvOXafK39cW5YZA9b9bzinu9cw Dl_167765_;
tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window_bcV9cH9cz5aDHcWv0qT6P9bTQ;
tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* render_eomdUYXdRHV3qofmMcQXsg;
tyArray_A4GTsBKrn1StyjIPYWAj9bw board_Q27IYS8tE2mNpatfJsUARg;
tyArray_tBzCxVJJXe7fyzaDdi730A activeTetronimo_fS1cTH9bIkxJWUZjq54mShA;
tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA activeRotation_WKUsqXMLGskGP9aTPx7iYKw;
extern tyProc_1K9aSViCbSUpZMtRI9aw9a2Rg Dl_168356_;
extern tyProc_eGPD9aEHv9b8sVQMCQaPsYkg Dl_167811_;
tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture_2i9cIV2c7Ae9a9bdqnbkbVUdA;
extern tyProc_0icUM9coigCdz0HL3vd9bFCw Dl_172621_;
extern tyProc_uEPg0xGcL9ao0XgF3q7VnpA Dl_167995_;
tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug evt_nOp9bCcz5qteY79a5h1ySMCA;
extern tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ;
NIM_BOOL runGame_fF4Gda29bTFaI9aEn3vyBtxA;
tyObject_FpsManager_K9c6YTNaeSVqIm8VozHdXPQ fpsman_HPssCyMWKT1wC6ZFn0TK2Q;
extern tyProc_cfgfzj4BFRc9cgaCE88zYLQ Dl_171222_;
extern tyProc_b9aXpKFbsyZ0PIk3aYRVCAA Dl_168605_;
NF dt_ahKx3mE3rX1nEvNQx5FrtQ;
extern tyProc_2nApE2oRVV9bdZ01fOBEbDg Dl_171231_;
extern tyProc_BzAZji9bzvN1k9ae25rIlb8A Dl_167617_;
extern tyProc_zHpDbFN4o9bvP9cAphXAUHXg Dl_168017_;
extern tyProc_9a8AalbnAaIxTUMpzQQqpjw Dl_168036_;
extern tyProc_2nApE2oRVV9bdZ01fOBEbDg Dl_171239_;
extern tyProc_9a8AalbnAaIxTUMpzQQqpjw Dl_167648_;
extern tyProc_T629bWTbvDFNyKAaO0BGGIQ Dl_168388_;
NIM_CONST tyArray_tBzCxVJJXe7fyzaDdi730A SHAPE_I_L7tObeplXnEOA2nublpGBA = {{{((NI) 0),
((NI) 0)}
,
{((NI) 0),
((NI) 1)}
,
{((NI) 0),
((NI) 2)}
,
{((NI) 0),
((NI) 3)}
}
,
{{((NI) 0),
((NI) 0)}
,
{((NI) 1),
((NI) 0)}
,
{((NI) 2),
((NI) 0)}
,
{((NI) 3),
((NI) 0)}
}
,
{{((NI) 0),
((NI) 0)}
,
{((NI) 0),
((NI) 1)}
,
{((NI) 0),
((NI) 2)}
,
{((NI) 0),
((NI) 3)}
}
,
{{((NI) 0),
((NI) 0)}
,
{((NI) 1),
((NI) 0)}
,
{((NI) 2),
((NI) 0)}
,
{((NI) 3),
((NI) 0)}
}
}
;
STRING_LITERAL(TM_wb2M869aF7F4XAtLMdG9cNOw_2, "x < 10 ", 7);
STRING_LITERAL(TM_wb2M869aF7F4XAtLMdG9cNOw_3, "y < 20 ", 7);
NIM_CONST tyArray_A4GTsBKrn1StyjIPYWAj9bw TM_wb2M869aF7F4XAtLMdG9cNOw_5 = {{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
,
{((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7),
((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7)}
}
;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isBlockAt_4b9clJUjy444rNQS4Pl9ccHw)(tyArray_A4GTsBKrn1StyjIPYWAj9bw board, NU x, NU y) {
	NIM_BOOL result;
	nimfr_("isBlockAt", "board.nim");
	result = (NIM_BOOL)0;
	nimln_(41, "board.nim");
	{
		if (!!(((NU64)(x) < (NU64)(((NU) 10))))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_wb2M869aF7F4XAtLMdG9cNOw_2));
	}
	LA3_: ;
	nimln_(42, "board.nim");
	{
		if (!!(((NU64)(y) < (NU64)(((NU) 20))))) goto LA7_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_wb2M869aF7F4XAtLMdG9cNOw_3));
	}
	LA7_: ;
	nimln_(43, "board.nim");
	if ((NU)(y) > (NU)(19)) raiseIndexError();
	if ((NU)(x) > (NU)(9)) raiseIndexError();
	result = (board[(y)- 0][(x)- 0] == ((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 7));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, dropBlockAt_KP9aYeB9cuk5QYM2zV2M2E9cA)(tyArray_dGkDOlaIzDUcymySNQBeNg* board, NU x, NU y) {
	nimfr_("dropBlockAt", "board.nim");
	nimln_(52, "board.nim");
	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T4_ = isBlockAt_4b9clJUjy444rNQS4Pl9ccHw(board, x, (NU)((NU64)(y) + (NU64)(((NI) 1))));
		T3_ = !(T4_);
		if (!(T3_)) goto LA5_;
		T3_ = ((NU64)(y) < (NU64)(((NU) 19)));
		LA5_: ;
		if (!T3_) goto LA6_;
		nimln_(53, "board.nim");
		if ((NU)((NU)((NU64)(y) + (NU64)(((NI) 1)))) > (NU)(19)) raiseIndexError();
		if ((NU)(x) > (NU)(9)) raiseIndexError();
		if ((NU)(y) > (NU)(19)) raiseIndexError();
		if ((NU)(x) > (NU)(9)) raiseIndexError();
		board[((NU)((NU64)(y) + (NU64)(((NI) 1))))- 0][(x)- 0] = board[(y)- 0][(x)- 0];
	}
	LA6_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA, rotateLeft_WhYUm29bN1IvB6kJwPoZzIg)(tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA currentRotation) {
	tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA result;
	nimfr_("rotateLeft", "board.nim");
	result = (tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA)0;
	nimln_(56, "board.nim");
	switch (currentRotation) {
	case ((tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA) 0):
	{
		nimln_(58, "board.nim");
		result = ((tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA) 3);
	}
	break;
	case ((tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA) 1):
	{
		nimln_(60, "board.nim");
		result = ((tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA) 0);
	}
	break;
	case ((tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA) 2):
	{
		nimln_(62, "board.nim");
		result = ((tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA) 1);
	}
	break;
	case ((tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA) 3):
	{
		nimln_(64, "board.nim");
		result = ((tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA) 2);
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA, rotateRight_WhYUm29bN1IvB6kJwPoZzIg_2)(tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA currentRotation) {
	tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA result;
	nimfr_("rotateRight", "board.nim");
	result = (tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA)0;
	nimln_(67, "board.nim");
	switch (currentRotation) {
	case ((tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA) 0):
	{
		nimln_(69, "board.nim");
		result = ((tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA) 1);
	}
	break;
	case ((tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA) 1):
	{
		nimln_(71, "board.nim");
		result = ((tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA) 2);
	}
	break;
	case ((tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA) 2):
	{
		nimln_(73, "board.nim");
		result = ((tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA) 3);
	}
	break;
	case ((tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA) 3):
	{
		nimln_(75, "board.nim");
		result = ((tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA) 0);
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ, generateTetronimoType_O9atHRoChfVK9bcx9cFIsM4nA)(void) {
	tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ result;
	NI T1_;
	nimfr_("generateTetronimoType", "board.nim");
	result = (tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ)0;
	nimln_(81, "board.nim");
	randomize_RtUZt2O8eA6Y5pFWOsdgjg();
	nimln_(82, "board.nim");
	T1_ = (NI)0;
	T1_ = rand_F1qFFP53BvbP4L65Kn9bG1w_2(((NI) 6));
	switch (T1_) {
	case ((NI) 0):
	{
		nimln_(84, "board.nim");
		result = ((tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ) 0);
	}
	break;
	case ((NI) 1):
	{
		nimln_(86, "board.nim");
		result = ((tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ) 1);
	}
	break;
	case ((NI) 2):
	{
		nimln_(88, "board.nim");
		result = ((tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ) 2);
	}
	break;
	case ((NI) 3):
	{
		nimln_(90, "board.nim");
		result = ((tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ) 3);
	}
	break;
	case ((NI) 4):
	{
		nimln_(92, "board.nim");
		result = ((tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ) 4);
	}
	break;
	case ((NI) 5):
	{
		nimln_(94, "board.nim");
		result = ((tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ) 5);
	}
	break;
	case ((NI) 6):
	{
		nimln_(96, "board.nim");
		result = ((tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ) 6);
	}
	break;
	default:
	{
		nimln_(98, "board.nim");
		result = ((tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ) 0);
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, newTetronimo_rx8mlrdpgisQw9aihwsqf6A)(tyArray_tBzCxVJJXe7fyzaDdi730A Result) {
	tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ T1_;
	nimfr_("newTetronimo", "board.nim");
	chckNil((void*)Result);
	memset((void*)Result, 0, sizeof(Result));
	nimln_(101, "board.nim");
	T1_ = (tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ)0;
	T1_ = generateTetronimoType_O9atHRoChfVK9bcx9cFIsM4nA();
	switch (T1_) {
	case ((tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ) 0):
	{
		nimln_(103, "board.nim");
		memcpy((void*)Result, (NIM_CONST void*)SHAPE_I_L7tObeplXnEOA2nublpGBA, sizeof(tyArray_tBzCxVJJXe7fyzaDdi730A));
	}
	break;
	case ((tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ) 1):
	{
		nimln_(105, "board.nim");
		memcpy((void*)Result, (NIM_CONST void*)SHAPE_I_L7tObeplXnEOA2nublpGBA, sizeof(tyArray_tBzCxVJJXe7fyzaDdi730A));
	}
	break;
	case ((tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ) 2):
	{
		nimln_(107, "board.nim");
		memcpy((void*)Result, (NIM_CONST void*)SHAPE_I_L7tObeplXnEOA2nublpGBA, sizeof(tyArray_tBzCxVJJXe7fyzaDdi730A));
	}
	break;
	case ((tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ) 3):
	{
		nimln_(109, "board.nim");
		memcpy((void*)Result, (NIM_CONST void*)SHAPE_I_L7tObeplXnEOA2nublpGBA, sizeof(tyArray_tBzCxVJJXe7fyzaDdi730A));
	}
	break;
	case ((tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ) 4):
	{
		nimln_(111, "board.nim");
		memcpy((void*)Result, (NIM_CONST void*)SHAPE_I_L7tObeplXnEOA2nublpGBA, sizeof(tyArray_tBzCxVJJXe7fyzaDdi730A));
	}
	break;
	case ((tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ) 5):
	{
		nimln_(113, "board.nim");
		memcpy((void*)Result, (NIM_CONST void*)SHAPE_I_L7tObeplXnEOA2nublpGBA, sizeof(tyArray_tBzCxVJJXe7fyzaDdi730A));
	}
	break;
	case ((tyEnum_TetronimoType_bBAQOstaBnltdTElP169clQ) 6):
	{
		nimln_(115, "board.nim");
		memcpy((void*)Result, (NIM_CONST void*)SHAPE_I_L7tObeplXnEOA2nublpGBA, sizeof(tyArray_tBzCxVJJXe7fyzaDdi730A));
	}
	break;
	}
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, insertShape_9ce7hHobx9a9cOfNVjg17o7zQ)(tyArray_dGkDOlaIzDUcymySNQBeNg* board, tyArray_tBzCxVJJXe7fyzaDdi730A Result) {
	tyArray_tBzCxVJJXe7fyzaDdi730A tetronimo;
	nimfr_("insertShape", "board.nim");
	chckNil((void*)Result);
	memset((void*)Result, 0, sizeof(Result));
	memset((void*)tetronimo, 0, sizeof(tetronimo));
	nimln_(118, "board.nim");
	newTetronimo_rx8mlrdpgisQw9aihwsqf6A(tetronimo);
	{
		tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ b;
		tyArray_oxvy57QiwK9c9a12Qd7kQzlQ colontmp_;
		NI i;
		memset((void*)(&b), 0, sizeof(b));
		memset((void*)colontmp_, 0, sizeof(colontmp_));
		nimln_(119, "board.nim");
		memcpy((void*)colontmp_, (NIM_CONST void*)tetronimo[(((NI) 0))- 0], sizeof(tyArray_oxvy57QiwK9c9a12Qd7kQzlQ));
		nimln_(2199, "system.nim");
		i = ((NI) 0);
		nimln_(2200, "system.nim");
		{
			if (!(((NI) (i)) <= ((NI) 3))) goto LA4_;
			{
				nimln_(2201, "system.nim");
				while (1) {
					NI TM_wb2M869aF7F4XAtLMdG9cNOw_4;
					nimln_(2202, "system.nim");
					b = colontmp_[(i)- 0];
					if ((NU)(b.Field1) > (NU)(19)) raiseIndexError();
					if ((NU)(b.Field0) > (NU)(9)) raiseIndexError();
					nimln_(120, "board.nim");
					board[(b.Field1)- 0][(b.Field0)- 0] = ((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 0);
					nimln_(2203, "system.nim");
					{
						if (!(((NI) 3) <= ((NI) (i)))) goto LA10_;
						goto LA6;
					}
					LA10_: ;
					nimln_(2204, "system.nim");
					TM_wb2M869aF7F4XAtLMdG9cNOw_4 = addInt(i, ((NI) 1));
					if (TM_wb2M869aF7F4XAtLMdG9cNOw_4 < 0 || TM_wb2M869aF7F4XAtLMdG9cNOw_4 > 3) raiseOverflow();
					i = (NI)(TM_wb2M869aF7F4XAtLMdG9cNOw_4);
				}
			} LA6: ;
		}
		LA4_: ;
	}
	nimln_(121, "board.nim");
	memcpy((void*)Result, (NIM_CONST void*)tetronimo, sizeof(tyArray_tBzCxVJJXe7fyzaDdi730A));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ, getBlockTexture_zOaZQisd5oWhqujp21WGMQ)(tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg color) {
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ result;
	nimfr_("getBlockTexture", "tetris.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(47, "tetris.nim");
	switch (color) {
	case ((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 0):
	{
		nimln_(49, "tetris.nim");
		result = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int) 0), ((int) 0), ((int) 32), ((int) 32));
	}
	break;
	case ((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 1):
	{
		nimln_(51, "tetris.nim");
		result = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int) 32), ((int) 0), ((int) 32), ((int) 32));
	}
	break;
	case ((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 2):
	{
		nimln_(53, "tetris.nim");
		result = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int) 64), ((int) 0), ((int) 32), ((int) 32));
	}
	break;
	case ((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 3):
	{
		nimln_(55, "tetris.nim");
		result = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int) 0), ((int) 32), ((int) 32), ((int) 32));
	}
	break;
	case ((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 4):
	{
		nimln_(57, "tetris.nim");
		result = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int) 32), ((int) 32), ((int) 32), ((int) 32));
	}
	break;
	case ((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 5):
	{
		nimln_(59, "tetris.nim");
		result = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int) 64), ((int) 32), ((int) 32), ((int) 32));
	}
	break;
	case ((tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg) 6):
	{
		nimln_(61, "tetris.nim");
		result = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int) 0), ((int) 64), ((int) 32), ((int) 32));
	}
	break;
	default:
	{
		nimln_(63, "tetris.nim");
		result = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int) 32), ((int) 64), ((int) 32), ((int) 32));
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, drawBlock_lNcFlsekAhGuxAXvCEQ87A)(tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg color, NU x, NU y) {
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ source;
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ dest;
	NI TM_wb2M869aF7F4XAtLMdG9cNOw_6;
	NI TM_wb2M869aF7F4XAtLMdG9cNOw_7;
	tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw T1_;
	nimfr_("drawBlock", "tetris.nim");
	nimln_(69, "tetris.nim");
	source = getBlockTexture_zOaZQisd5oWhqujp21WGMQ(color);
	nimln_(70, "tetris.nim");
	TM_wb2M869aF7F4XAtLMdG9cNOw_6 = mulInt(((NI32) 32), ((int) (x)));
	if (TM_wb2M869aF7F4XAtLMdG9cNOw_6 < (-2147483647 -1) || TM_wb2M869aF7F4XAtLMdG9cNOw_6 > 2147483647) raiseOverflow();
	TM_wb2M869aF7F4XAtLMdG9cNOw_7 = mulInt(((NI32) 32), ((int) (y)));
	if (TM_wb2M869aF7F4XAtLMdG9cNOw_7 < (-2147483647 -1) || TM_wb2M869aF7F4XAtLMdG9cNOw_7 > 2147483647) raiseOverflow();
	dest = rect_GH33Rh9bTnVBRLuu9bU7xoyA((NI32)(TM_wb2M869aF7F4XAtLMdG9cNOw_6), (NI32)(TM_wb2M869aF7F4XAtLMdG9cNOw_7), ((int) 32), ((int) 32));
	nimln_(71, "tetris.nim");
	T1_ = (tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
	T1_ = Dl_167995_(render_eomdUYXdRHV3qofmMcQXsg, texture_2i9cIV2c7Ae9a9bdqnbkbVUdA, (&source), (&dest), 0.0, NIM_NIL, ((int) 0));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, drawBoard_plavXhyyiBCgWhKKV5uZbA)(tyArray_A4GTsBKrn1StyjIPYWAj9bw board) {
	nimfr_("drawBoard", "tetris.nim");
	{
		NU64 rowIndex;
		NU64 res;
		rowIndex = (NU64)0;
		nimln_(2059, "system.nim");
		res = 0ULL;
		{
			nimln_(2060, "system.nim");
			while (1) {
				if (!((NU64)(res) <= (NU64)(19ULL))) goto LA3;
				nimln_(2061, "system.nim");
				rowIndex = res;
				{
					NU64 colIndex;
					NU64 res_2;
					colIndex = (NU64)0;
					nimln_(2059, "system.nim");
					res_2 = 0ULL;
					{
						nimln_(2060, "system.nim");
						while (1) {
							tyEnum_BlockColor_yaLNi5KJ8bY26XS5B71Uyg b;
							if (!((NU64)(res_2) <= (NU64)(9ULL))) goto LA6;
							nimln_(2061, "system.nim");
							colIndex = res_2;
							nimln_(76, "tetris.nim");
							if ((NU)(rowIndex) > (NU)(19)) raiseIndexError();
							if ((NU)(colIndex) > (NU)(9)) raiseIndexError();
							b = board[(rowIndex)- 0][(colIndex)- 0];
							nimln_(77, "tetris.nim");
							drawBlock_lNcFlsekAhGuxAXvCEQ87A(b, ((NU) (colIndex)), ((NU) (rowIndex)));
							nimln_(2062, "system.nim");
							res_2 += ((NI) 1);
						} LA6: ;
					}
				}
				res += ((NI) 1);
			} LA3: ;
		}
	}
	popFrame();
}

static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y) {
	NF result;
	nimfr_("/", "system.nim");
	result = (NF)0;
	nimln_(3498, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

static N_INLINE(void, destroy_sFvfWODyHxg46OuBtGyU8Qtetris)(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window) {
	nimfr_("destroy", "sdl2.nim");
	nimln_(1742, "sdl2.nim");
	Dl_168388_(window);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_posixDatInit000();
	stdlib_timesDatInit000();
	stdlib_randomDatInit000();
	stdlib_macrosDatInit000();
	stdlib_unsignedDatInit000();
	sdl2_sdl2DatInit000();
	sdl2_gfxDatInit000();
	sdl2_imageDatInit000();
	tetrisDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_posixInit000();
	stdlib_timesInit000();
	stdlib_randomInit000();
	stdlib_macrosInit000();
	stdlib_unsignedInit000();
	sdl2_sdl2Init000();
	sdl2_gfxInit000();
	sdl2_imageInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw T1_;
	nimfr_("tetris", "tetris.nim");
	nimln_(7, "tetris.nim");
	T1_ = (tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
	T1_ = Dl_167765_(((int) 65535));
	T1_;
	nimln_(16, "tetris.nim");
	window_bcV9cH9cz5aDHcWv0qT6P9bTQ = Dl_168356_("Tetris", ((int) 100), ((int) 100), ((int) 320), ((int) 640), ((unsigned int) 4));
	nimln_(17, "tetris.nim");
	render_eomdUYXdRHV3qofmMcQXsg = Dl_167811_(window_bcV9cH9cz5aDHcWv0qT6P9bTQ, ((int) -1), ((NI32) 14));
	nimln_(18, "tetris.nim");
	texture_2i9cIV2c7Ae9a9bdqnbkbVUdA = Dl_172621_(render_eomdUYXdRHV3qofmMcQXsg, "tetris.png");
	nimln_(20, "tetris.nim");
	memcpy((void*)board_Q27IYS8tE2mNpatfJsUARg, (NIM_CONST void*)TM_wb2M869aF7F4XAtLMdG9cNOw_5, sizeof(tyArray_A4GTsBKrn1StyjIPYWAj9bw));
	nimln_(43, "tetris.nim");
	newTetronimo_rx8mlrdpgisQw9aihwsqf6A(activeTetronimo_fS1cTH9bIkxJWUZjq54mShA);
	nimln_(44, "tetris.nim");
	activeRotation_WKUsqXMLGskGP9aTPx7iYKw = ((tyEnum_TetronimoRotation_8XeQUJTMTHXdD9bwwSCPZIA) 0);
	nimln_(66, "tetris.nim");
	insertShape_9ce7hHobx9a9cOfNVjg17o7zQ(board_Q27IYS8tE2mNpatfJsUARg, activeTetronimo_fS1cTH9bIkxJWUZjq54mShA);
	nimln_(80, "tetris.nim");
	evt_nOp9bCcz5qteY79a5h1ySMCA = defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ;
	nimln_(81, "tetris.nim");
	runGame_fF4Gda29bTFaI9aEn3vyBtxA = NIM_TRUE;
	nimln_(83, "tetris.nim");
	Dl_171222_((&fpsman_HPssCyMWKT1wC6ZFn0TK2Q));
	{
		nimln_(86, "tetris.nim");
		while (1) {
			int T12_;
			tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw T13_;
			int T14_;
			int T15_;
			if (!runGame_fF4Gda29bTFaI9aEn3vyBtxA) goto LA3;
			{
				nimln_(87, "tetris.nim");
				while (1) {
					tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg T6_;
					NIM_BOOL T7_;
					T6_ = (tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg)0;
					T6_ = Dl_168605_((&evt_nOp9bCcz5qteY79a5h1ySMCA));
					T7_ = (NIM_BOOL)0;
					T7_ = toBool_3fq5Y9cfgYx8q7J9ba6TTYbQ(T6_);
					if (!T7_) goto LA5;
					nimln_(88, "tetris.nim");
					{
						if (!(evt_nOp9bCcz5qteY79a5h1ySMCA.kind == ((tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 256))) goto LA10_;
						nimln_(89, "tetris.nim");
						runGame_fF4Gda29bTFaI9aEn3vyBtxA = NIM_FALSE;
						nimln_(90, "tetris.nim");
						goto LA4;
					}
					LA10_: ;
				} LA5: ;
			} LA4: ;
			dt_ahKx3mE3rX1nEvNQx5FrtQ = 0;
			nimln_(92, "tetris.nim");
			T12_ = (int)0;
			T12_ = Dl_171231_((&fpsman_HPssCyMWKT1wC6ZFn0TK2Q));
			dt_ahKx3mE3rX1nEvNQx5FrtQ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(((NI) (T12_)), ((NI) 1000));
			nimln_(94, "tetris.nim");
			T13_ = (tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
			T13_ = Dl_167617_(render_eomdUYXdRHV3qofmMcQXsg, ((NU8) 110), ((NU8) 132), ((NU8) 174), ((NU8) 255));
			nimln_(95, "tetris.nim");
			T14_ = (int)0;
			T14_ = Dl_168017_(render_eomdUYXdRHV3qofmMcQXsg);
			nimln_(96, "tetris.nim");
			drawBoard_plavXhyyiBCgWhKKV5uZbA(board_Q27IYS8tE2mNpatfJsUARg);
			nimln_(97, "tetris.nim");
			Dl_168036_(render_eomdUYXdRHV3qofmMcQXsg);
			nimln_(99, "tetris.nim");
			T15_ = (int)0;
			T15_ = Dl_171239_((&fpsman_HPssCyMWKT1wC6ZFn0TK2Q));
		} LA3: ;
	}
	nimln_(101, "tetris.nim");
	Dl_167648_(render_eomdUYXdRHV3qofmMcQXsg);
	nimln_(102, "tetris.nim");
	destroy_sFvfWODyHxg46OuBtGyU8Qtetris(window_bcV9cH9cz5aDHcWv0qT6P9bTQ);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, tetrisDatInit000)(void) {
}

